### ISSUE TITLE
tutorial - Simple not working

### ISSUE THREAD

**Issue by karreem** [matchID-project/matchID-project.github.io#13]
Hi,

I am trying to use Match Id on an Ubuntu server and i am facing problems when I try to index deaths data.
error: <type 'exceptions.TypeError'> : search() got an unexpected keyword argument 'doc_type' line 594 deaths
![image](https://user-images.githubusercontent.com/9698997/64840797-fe833f80-d5fc-11e9-8f78-3e66c7871659.png)

Could you please help ?

Thx

**Comment by rhanka** [comment]
Fixed with update of backend after migration to 6 then 7 in 2020
